kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: qxp-home
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
  labels:
    app.kubernetes.io/version: v1
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        backend:
          serviceName: {{ .fullName }}
          servicePort: {{ .svcPort }}
      {{- end }}
  {{- end }}